version: "3.8"

services:
  solace:
    image: solace/solace-pubsub-standard
    container_name: solace
    shm_size: "1gb"
    ports:
      - "8080:8080"
      - "8008:8008"
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
    restart: unless-stopped
